version: "2.0"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./database-env:/docker-entrypoint-initdb.d
  php_symfony:
    image: 1992clement/php-symfony:1.0.7
    restart: always
    container_name: php-symfony
    depends_on:
      - db
    volumes:
      - ./app:/var/www/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
